package log;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;

public class Log {
	
	File log_file;
	PrintWriter wr;
	
	public Log() {
		
		try {
			
			log_file = new File("Log.txt");
			if(log_file.exists()) {
				log_file.delete();
			}
			log_file.createNewFile();
			
			wr = new PrintWriter(log_file);
			wr.write("//CMS version 1.0\n");
			wr.write("//Log created to produce compilation messages and to aid in"
					+ "debugging and configuration\n");
			wr.write("//Generated by BYU Bioinformatics, all rights reserved\n\n");
			
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	public void addLine(String args) {
		wr.write(args + "\n");
		wr.flush();
	}
	
	public void add(String args) {
		wr.write(args);
		wr.flush();
	}
	
	public void close() {
		wr.close();
	}
}
